# Generated by Django 5.1.13 on 2025-11-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='is_premium_only',
            field=models.BooleanField(default=False, help_text='Only premium users can view this pin'),
        ),
    ]
